name: Lint code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
      with:
        node-version-file: .node-version
        cache: "npm"
        check-latest: true

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint
