name: Lint code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: clytage/workflows/.github/workflows/pnpm-lint.yml@main
    secrets: inherit
