name: Publish package to NPM and GitHub registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: https://registry.npmjs.org/
            token_secret_key: NPM_TOKEN
          # - registry: https://npm.pkg.github.com/
          #   token_secret_key: GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: .node-version
          cache: "npm"
          check-latest: true
          registry-url: ${{ matrix.registry }}

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build and Compile TypeScript project
      #   run: npm run build

      - name: Publish package to npm and GitHub packages registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret_key] }}
